development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: wtg2
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  host: localhost
  database: wtg
  encoding: utf8