development:
  adapter: postgresql
  database: wtg1
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: wtg2
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  host: localhost
  database: wtg
  encoding: utf8