development:
  adapter: postgresql
  database: wtg_development
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: wtg_test
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  host: localhost
  database: wtg_production
  encoding: utf8